name: Deploy to EC2 on Main Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop model0-ui-container
            docker container rm model0-ui-container
            docker image rm model0-ui-image
            rm -rf $HOME/model0-ui
            git clone ${{ secrets.GIT_URL }}
            cd model0-ui
            docker build -t model0-ui-image .
            docker run -d -p 3000:3000 --name model0-ui-container model0-ui-image
