name: Deploy to EC2 on Main Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker system prune -a -f --volumes

            if [ "$(sudo docker ps -q -f name=model0-ui-container)" ]; then
              sudo docker stop model0-ui-container
            fi

            if [ "$(sudo docker ps -a -q -f name=model0-ui-container)" ]; then
              sudo docker container rm model0-ui-container
            fi

            if [ "$(sudo docker images -q model0-ui-image)" ]; then
              sudo docker image rm model0-ui-image
            fi

            rm -rf $HOME/model0-ui
            git clone ${{ secrets.GIT_URL }}
            cd model0-ui

            sudo docker build -t model0-ui-image .

            sudo docker run -d -p 3000:3000 --name model0-ui-container model0-ui-image
